name: kba_market_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9.21
  
  # Core Data Processing
  - pandas>=1.5.0
  - openpyxl>=3.0.0
  - xlrd>=2.0.0
  
  # Database & Storage
  - sqlalchemy>=1.4.0
  - psycopg2>=2.9.0
  
  # Development & Analysis
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipykernel>=6.0.0
  
  # Utilities
  - click>=8.0.0
  - pyyaml>=6.0
  
  # Development Tools
  - pytest>=7.0.0
  - black>=22.0.0
  - flake8>=5.0.0
  
  # Documentation
  - mkdocs>=1.4.0
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - python-dotenv>=0.19.0
    - great-expectations>=0.15.0
    - pandas-profiling>=3.0.0
    - pytest-cov>=4.0.0
    - mypy>=0.991
    - mkdocs-material>=8.0.0
    - mkdocs-mermaid2-plugin>=0.6.0 