site_name: KBA Market Analysis Documentation
site_description: Production-grade ETL pipeline for German vehicle registration data
site_url: https://kba-market-analysis.readthedocs.io/
repo_url: https://github.com/yedkowskij/kba_market_analysis
repo_name: company/kba_market_analysis

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - footnotes
  - md_in_html
  - attr_list
  - def_list
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#ffffff'

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: user-guide/installation.md
    - Quick Start: user-guide/quickstart.md
    - Configuration: user-guide/configuration.md
  - User Guide:
    - Data Sources: user-guide/data-sources.md
    - Processing Pipeline: user-guide/pipeline.md
    - Database Operations: user-guide/database.md
    - Analysis Workflows: user-guide/analysis.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Technical Reference:
    - Architecture: technical/architecture.md
    - Data Models: technical/data-models.md
    - ETL Processes: technical/etl-processes.md
    - Performance Tuning: technical/performance.md
    - Security: technical/security.md
  - API Reference:
    - Overview: api/overview.md
    - Data Processing: api/processing.md
    - Database: api/database.md
    - Utilities: api/utilities.md
  - Data Schemas:
    - FZ-1 Regional Data: schemas/fz1.md
    - FZ-2 Fuel Types: schemas/fz2.md
    - FZ-3 Commercial: schemas/fz3.md
    - FZ-8 Brand Statistics: schemas/fz8.md
    - FZ-10 Model Analysis: schemas/fz10.md
  - Contributing:
    - Development Setup: contributing/setup.md
    - Code Standards: contributing/standards.md
    - Testing: contributing/testing.md
    - Documentation: contributing/documentation.md

# Extra CSS/JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Copyright
copyright: Copyright &copy; 2024 Strategic Analytics Team

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yedkowskij/kba_market_analysis
    - icon: fontawesome/solid/envelope
      link: "artur.jodkowski@gmail.com"
    - icon: fontawesome/solid/envelope
      link: "jan@tarnaske.com"